Adapting plugin to SC v16.0.1
SocketCluster/sc-stateless-presence pull request #8
Opened 2020-04-27 00:41 UTC by fapbatista

Code adapted to be compatible with the most recent version of SocketCluster v16.0.1 - server and client adapted. Client library should be in separate repo.

2020-04-27 08:23 UTC, jondubois requested changes
Thanks for this PR. Overall looks great. I left some comments about some details.

There are a few parts where the logic/timing changes (not just the syntax) so these parts should be double checked.

2020-04-27 08:23 UTC, jondubois commented on client.js
> +    //socketChannel.watch(function (presencePacket) {});
This comment can be deleted.

2020-04-27 08:23 UTC, jondubois commented on client.js
> +    for await (let message of self.socket.listener('close')) {
The indentation throughout this block is inconsistent.

2020-04-27 08:23 UTC, jondubois commented on client.js
> +        Object.keys(self.channelUsers[channelName] || {}).forEach(function (username) {
Inconsistent indentation.

2020-04-27 08:23 UTC, jondubois commented on client.js
> +        await channel.listener('subscribe').once();
Awaiting for the subscribe here should not be necessary.
Also, if the subscription cannot be established because of bad internet connectivity, it could get stuck here (until socket disconnects). It's possible to provide a timeout to the `.once(timeoutMs)` function but then you have to handle the error.

But in any case, consuming data from a channel which is in pending state is allowed so waiting for subscription should not be necessary.

2020-04-27 08:23 UTC, jondubois commented on client.js
> +  self.socket.processPendingSubscriptions()
This logic is different from before. Maybe this line was added because of the `await channel.listener('subscribe').once();` which was added below but that should not be required either.

2020-04-27 08:23 UTC, jondubois commented on index.js
> +      if(action.newAuthState == action.socket.UNAUTHENTICATED){
Inconsistent spacing `if(` -> `if (`

2020-04-27 08:23 UTC, jondubois commented on index.js
> +      }else if(action.newAuthState == action.socket.AUTHENTICATED){
`}else if(` -> `} else if (`

2020-04-27 08:23 UTC, jondubois commented on index.js
> +      if(action.newAuthState == action.socket.UNAUTHENTICATED){
`if(` -> `if (`

2020-04-27 08:23 UTC, jondubois commented on index.js
> +      }else if(action.newAuthState == action.socket.AUTHENTICATED){
`}else if(` -> `} else if (`

2020-04-27 08:23 UTC, jondubois commented on index.js
> +      if(action.code == 1000){
Why only if `code == 1000`? Before, it also accounted the case of failed connection because of bad internet connectivity. Also the spacing is inconsistent with other `if` statements.

2020-04-27 08:23 UTC, jondubois commented on index.js
> +      }else{
`}else{` -> `} else {`

2020-04-27 16:44 UTC, fapbatista commented
@jondubois Hello Johnathan, thanks for taking the time to review my pull request. I've reviewed the changes you suggested and improved on the points you noted. If you have any other suggestion feel free to let me know. Kind regards.

2020-04-27 22:38 UTC, fapbatista commented on client.js
> -  self.socket.processPendingSubscriptions()
@jondubois Jonathan, I noticed something peculiar on the client side code: if i remove this line the channel will never go out of the pending state. That is, when I call this.socket.subscribe or by retrieving later the channel with this.socket.channel it returns the state pending forever. When this function is called right after subscription it works as it is supposed to. I suppose processPendingSubscription is something similar to a lifecycle method of the channel, my question is: when will this be called automatically and when should i call it explicitly? Thanks!

2020-04-28 09:12 UTC, merged

2020-04-28 10:54 UTC, jondubois commented
I merged it for now but there are a few issues. One problem was that inside the middleware it was using `return` instead of `continue` and that's what was causing the subscription to be stuck in pending.

2020-04-28 11:00 UTC, fapbatista commented
> I merged it for now but there are a few issues which I will fix. One problem was that inside the middleware it was using `return` instead of `continue` and that's what was causing the subscription to be stuck in pending.

Hello @jondubois I will watch your changes to the repository so I can learn more from you. I will be happy to review your changes when you find the time to correct the mistakes I have made. Thanks!

2020-04-28 15:50 UTC, jondubois commented
@fapbatista OK I made the fixes and published to npm as v2.0.0.

I was thinking it would be good to update the API so that it doesn't use callbacks (e.g. `trackPresence(channelName, callback)` function) and uses streams instead but that can be done later.

2020-04-28 16:30 UTC, fapbatista commented
@jondubois I will see if I know how to do that in those methods where there are still callbacks. Probably I will have to expose the streams using stream-demux, right?  Also, thinking here the method that returns user list might not be scalable as the number of users in a channel grow, but I couldn't think of an efficient way returning those.

2020-04-28 16:34 UTC, fapbatista commented
@jondubois Looking at your last changes I think I have an idea on how to do that. I will work on it tonight and send a new PR removing points where we still have callbacks.

2020-04-28 17:07 UTC, jondubois commented
@fapbatista Nice. Yes you can use `stream-demux`; ideally, you should have a single `StreamDemux` instance for all the different channel presence trackers, but you use the `demux.stream(presenceChannelName);` to create sub-streams. When you create a stream like this (as sub-streams using StreamDemux), you don't need to manage those; they are just branches of the main stream so you don't have to clean them up explicitly which is nice.